name: Build and publish the Java SDK
on: [push]
#  push:
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+*' # v0.0.1 - this syntax of tags is supported

jobs:
  build-and-publish-java-sdk:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Publish to Github packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
    env:
      AWS_S3_URL: ${{ secrets.ARTIFACTS_UPLOADER_S3_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_UPLOADER_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_UPLOADER_SECRET_ACCESS_KEY }}
#      VERSION_TAG: ${{ github.ref_name }}
